package id.ac.poliban.mi.atul.listpahlawan;

import java.util.ArrayList;
import java.util.List;

public class HeroData {
    static List<Hero> getAllHero() {
        List<Hero> data = new ArrayList<>();
        {
            data.add(new Hero("https://thegorbalsla.com/wp-content/uploads/2018/10/asad-syamsul-arif-700x496.jpg", "As’ad Syamsul", "K.H.R As’ad Syamsul Arifin lahir pada tahun 1897 di kota mekah dan wafat pada tanggal 4 Agustus 1990 di Situbondo jawa Timur tepat di usia 93 tahun. K.H.R As’ad adalah seorang ulama besar sekaligus seorang tokoh Nahdlatul Ulama dan terakhir menjabat sebagai Dewan Penasehat (musytasar) dan beliau menjabat di Nahdlatul Ulama hingga sampai akhir hayatnya. Selain menjabat sebagai tokoh besar di Nahdlatul Ulama, beliau juga pengasuh sebuah pondok pesantren Salafiyah Syafi’iyah di Desa Sukorejo, Kecamatan Asembagus, Kabupaten Situbondo, Jawa Timur."));
            data.add(new Hero("https://thegorbalsla.com/wp-content/uploads/2018/10/cut-mutia-700x539.jpg", "Cut Mutia", "Cut Mutia lahir pada tahun 1970 di Keureutoe, Pirak, Aceh Utara dan wafat pada tanggal 24 Oktober 1910. Cut Mutia adalah seorang tokoh pahlawan nasional Indonesia dari Aceh. Pada awalnya Cut Mutia merupakan pahlawan dalam perlawanan Belanda bersama suaminya yaitu Teuku Muhammad atau Teuku Tjik Tunong."));
            data.add(new Hero("https://thegorbalsla.com/wp-content/uploads/2018/10/cut-nyak-dhien-700x432.jpg", "Cut Nyak Dhien", "Cut Nyak Dhien merupakan seorang pahlawan Indonesia yang dilahirkan pada tahu 1984 di Lampadag, kerajaan Aceh. Beliau merupakan salah satu pahlawan wanita yang memiliki semangat tinggi dalam melawan Belanda. Cut Nyak Dhien memiliki seorang suami yaitu Teuku Umar. Beliau juga salah satu pahlawan nasional Indonesia yang gugur di medan perang. Teuku Umar wafat pada tanggal tanggal 11 januari tahun 1899. Sedangkan Cut Nyak Dhien sendiri wafat pada tanggal 6 November tahun 1908 dan dimakamkan di Sumedang, Jawa Barat. Cut Nyak Dhien juga bergabung dengan para pejuang Aceh yang pada saat itu belum tertangkap. Nama Cut Nyak Dhien kini namanya diabadikan sebagai Bandar Udara Cut Nyak Dhien Nagan Raya di Meulaboh."));
            data.add(new Hero("https://thegorbalsla.com/wp-content/uploads/2018/10/idham-chalid-700x499.jpg", "Idham Chalid", "Dr. KH. Idham Khalid adalah pahlawan nasionala Indonesia yang lahir pada tanggal 27 Agustus 1921 di Satui, Kalimantan Selatan. Belaiu wafat pada tanggal 11 Juli 2010 tepat di usia 88 tahun. Idham Khalid merupakan salah satu pahlawan yang sangat berpengaruh pada saat masanya. Idham khalid merupakan tokoh paling muda pada saat memimpin ormas dan belia salah satu orang yang menjabat paling lama. Idham Khalid selain terkenal sebagai tokoh besar pada zaman orde baru maupun orde lama. Ormas tersebut berdiri pada tahun 1926. Dalam ormas tersebut diberi logo bola dua dan bintang Sembilan. Idham melewati karirnya dengan sangat cemerlang hingga pada puncak impiannya."));
            data.add(new Hero("https://thegorbalsla.com/wp-content/uploads/2018/10/jendral-sudirman-700x554.jpg", "Jendral Sudirman", "Jendral Sudirman adalah seorang pahlawan nasional Indonesia yang memiliki jabatan sebagai Jendral Besar TNI Anumerta Sudirman. Beliau mendapatkan gelarnya di usia 31 tahun. Jendral Sudirman adalah seorang yang sangat berjasa pada masa Revolusi Nasional Indonesia. Pahlawan yang terkenal dengan perang gerilya dan serangan pada tanggal 1 Maret 1949. Jendral Sudirman adalah seorang pahlawan nasional Indonesia yang memiliki jabatan sebagai Jendral Besar TNI Anumerta Sudirman. Beliau mendapatkan gelarnya di usia 31 tahun. Jendral Sudirman adalah seorang yang sangat berjasa pada masa Revolusi Nasional Indonesia. Pahlawan yang terkenal dengan perang gerilya dan serangan pada tanggal 1 Maret 1949."));
            data.add(new Hero("https://thegorbalsla.com/wp-content/uploads/2018/10/john-lie-700x512.jpg", "John Lie", "John Lie lahir di Menado pada tanggal 9 Maret 1911dari keluaga Tionghoa. Pada awalnya John merupan seorang mualim dari di pelayaran niaga milik pemerintahan Belanda, Koninklijke Pakertvaart Maatchappij atau sering disingkat KPM yang kemudian bergabung dengan ALRI. Pada saat itu John sedang bertugas di Cilacap. John berhasil membersihkan ranjau yang ditanam oleh Jepang, pada masa itu untuk menghalau pasukan sekutu. Atas jasanya John dinaikkan pangkatnya menjadi Mayor. Dengan menggunakan kapal motornya, John dengan beraninya menembus blockade laut yang di sekitar perairan Selat Malaka yang dilakukan oleh Angkatan Laut Belanda."));
            data.add(new Hero("https://thegorbalsla.com/wp-content/uploads/2018/10/kartini-700x547.jpg", "Kartini", "Raden Ayu Kartini atau Raden Adjeng Kartini adalah salah satu pahlawan nasional wanita yang sangat berjasa untuk bangsa ini. Kartini hampir seluruh hidupnya dihabiskan untuk memperjuangkan kesetaraan untuk kaumnya. Belia juga dikenala sebagai pelopor kebangkitan wanita pribumi. Raden Adjeng Kartini lahir di Jepara pada tanggal 21 April 1879. Pada tanggal 12 November 1903 Kartini menikah dengan seorang bupati rembang Singgih Djojo Adhiningrat yaitu seorang yang sudah pernah memiliki tiga istri. Setelah menikah, Kartini hijrah ke Rembang mengikuti suaminya. Beliau diberi kebebasan oleh suaminya untuk mendirikan sekolah untuk wanita di daerah komplek kabupaten Rembang dan bangunan tersebut sekarang dijadikan sebagai Gedung Pramuka."));
            data.add(new Hero("https://thegorbalsla.com/wp-content/uploads/2018/10/KH-ahmad-dahlan-700x538.jpg", "K.H Ahmad Dahlan", "Muhammad Darwis atau Ahmad Dahlan adalah salah satu pahlawan nasional Indonesia. Beliau lahir pada tanggal 1 Agustus 1868 di kota Yogyakarta. Beliau merupakan putera ke empat dari tujuh bersaudari dari keluarga K.H Abu Bakar. K.H Abu bakar adalah seorang ulama besar dan khatib tersohor di Masjid Besar Kesultanan Yogyakarta. Pada saat usianya masih 15 tahun, beliau pergi haji dan tinggal di mekah selama 5 tahun. Pada periode itu Ahmad Dahlan mulai berinteraksi dengan pemikiran islam. Pada tanggal 18 November 1912 beliau mendirikan sebuah organisasi Muhammadiyah di Kauman, Yogyakarta. Beliau ingin mengadakan pembaharuan dalam berfikir dan beramal sesuai dengan tuntunan agama islam. Beliau ingin mengajak umat islam kembali hidup sesuai dengan ajaran islam menurut tuntunan al- Qur’an dan al- Hadist."));
            data.add(new Hero("https://thegorbalsla.com/wp-content/uploads/2018/10/ki-hajar-dewantara-700x549.jpg", "Ki Hajar Dewantara", "Raden Mas Soewardi Soerjaningrat sejak tahun 1922 namanya diganti menadi Ki Hajar Dewantara. Beliau adalah pahlawan nasional Indonesia yang merupakan seorang aktivis pergerkan kemerdekaan Indonesia, politisi, kolumnis dan juga seorang pelopor dalam bidang pendidikan kaum pribumi pada masa penjajahan belanda. Beliau adalah pendiri Perguruan Tinggi Taman Siswa di Yogyakarta. Suatu lembaga pendidikan yang memberikan kesempatan pada masyarakat pribumi untuk mendapatkan hak pendidikan seperti halnya seorang priyayi ataupun orang- orang Belanda."));
            data.add(new Hero("https://thegorbalsla.com/wp-content/uploads/2018/10/lafran-pane-700x474.jpg", "Lafran Pane", "Lafran Pane lahir pada tanggal 5 Februari 1922 di Padang Sidempuan. Tetapi menurut berbagai tulisan sebelumnya, beliau lahir pada tanggal 12 April 1923 di kampung Pangurabaan, Kecamatan Sipirok yang terletak di kaki gunung Sibualbuali ibu kota Tapanuli Selatan. Lafran Pane memulai pendidikannya di Pesantren Muhammdiyah Sipirok yang dilanjutkan oleh Pesantern K.H Ahmad Dahlan di kampung Setia dekat dengan Desa Parsominan Sipirok. Beliau merupakan salah satu pendiri Himpunan Mahasiswa Islam (HMI) yang didirikan pada tanggal 5 Februari 1957."));
        }
        return data;
    }
}